# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless

frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.12z

functions:
  hello:
    handler: handler.hello
